# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
safe: true
lsi: false
markdown: kramdown
excerpt_separator: "\n\n"
encoding: UTF-8
ASSET_PATH: assets

kramdown:
    input: GFM
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        default_lang: plaintext

title : 胖梁的技术笔记
author :
    name : 胖梁
    email : liang8305@gmail.com
    github : https://github.com/pangliang
    weibo : http://weibo.com/iamliangwei

image_dir: http://qiniucdn.zhaoxiaodan.com
production_url : http://www.zhaoxiaodan.com


######## for 3-Jekyll themes
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

sass:
    style: compressed

######## for 3-Jekyll  end themes

disqus :
    short_name : pangliang
